/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type ApplicationsOrderColumn =
  | 'ID'
  | 'DATE_CREATED'
  | 'TYPE'
  | 'STATE'
  | 'SUBMITTER'
  | 'GROUP_NAME'
  | 'MODIFIED_BY';

export const ApplicationsOrderColumn = {
  ID: 'ID' as ApplicationsOrderColumn,
  DATECREATED: 'DATE_CREATED' as ApplicationsOrderColumn,
  TYPE: 'TYPE' as ApplicationsOrderColumn,
  STATE: 'STATE' as ApplicationsOrderColumn,
  SUBMITTER: 'SUBMITTER' as ApplicationsOrderColumn,
  GROUPNAME: 'GROUP_NAME' as ApplicationsOrderColumn,
  MODIFIEDBY: 'MODIFIED_BY' as ApplicationsOrderColumn,
};
