/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationsOrderColumn } from './applicationsOrderColumn';
import { SortingOrder } from './sortingOrder';
import { AppState } from './appState';

export interface ApplicationsPageQuery {
  pageSize: number;
  offset: number;
  order: SortingOrder;
  sortColumn: ApplicationsOrderColumn;
  searchString?: string;
  includeGroupApplications?: boolean;
  getDetails?: boolean;
  states?: Array<AppState>;
  dateFrom?: string;
  dateTo?: string;
  userId?: number;
  groupId?: number;
}
