/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributePolicyCollection } from './attributePolicyCollection';

export interface AttributeRules {
  attributePolicyCollections?: Array<AttributePolicyCollection>;
  /**
   * Represents types of actions (READ, WRITE) that users can perform upon attributes and if they are critical globally or not.
   */
  criticalActions?: { [key: string]: boolean };
}
