/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents types of actions that users can perform upon attributes.
 */
export type AttributeAction = 'WRITE' | 'READ';

export const AttributeAction = {
  WRITE: 'WRITE' as AttributeAction,
  READ: 'READ' as AttributeAction,
};
