/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * type of destination, i.e. way of delivery of service settings
 */
export type DestinationType =
  | 'host'
  | 'email'
  | 'semail'
  | 'url'
  | 'user@host'
  | 'user@host:port'
  | 'service-specific'
  | 'user@host-windows'
  | 'host-windows-proxy';

export const DestinationType = {
  host: 'host' as DestinationType,
  email: 'email' as DestinationType,
  semail: 'semail' as DestinationType,
  url: 'url' as DestinationType,
  userhost: 'user@host' as DestinationType,
  userhostport: 'user@host:port' as DestinationType,
  service_specific: 'service-specific' as DestinationType,
  userhost_windows: 'user@host-windows' as DestinationType,
  host_windows_proxy: 'host-windows-proxy' as DestinationType,
};
