/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Resource } from './resource';
import { RichMember } from './richMember';
import { BanOnResource } from './banOnResource';

export interface EnrichedBanOnResource {
  resource?: Resource;
  member?: RichMember;
  ban?: BanOnResource;
}
