/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * currently supported formats are DOT and TGF
 */
export type GraphFileFormat = 'DOT' | 'TGF';

export const GraphFileFormat = {
  DOT: 'DOT' as GraphFileFormat,
  TGF: 'TGF' as GraphFileFormat,
};
