/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * admin roles for a group
 */
export type GroupAdminRoles = 'GROUPOBSERVER' | 'GROUPMEMBERSHIPMANAGER' | 'GROUPADMIN';

export const GroupAdminRoles = {
  GROUPOBSERVER: 'GROUPOBSERVER' as GroupAdminRoles,
  GROUPMEMBERSHIPMANAGER: 'GROUPMEMBERSHIPMANAGER' as GroupAdminRoles,
  GROUPADMIN: 'GROUPADMIN' as GroupAdminRoles,
};
