/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GroupMemberRelation {
  /**
   * member id
   */
  m?: number;
  /**
   * group id
   */
  g?: number;
  /**
   * source group id
   */
  sg?: number;
  /**
   * source group status
   */
  s?: string;
  /**
   * membership type
   */
  t?: string;
}
