/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type GroupsOrderColumn = 'ID' | 'NAME' | 'DESCRIPTION';

export const GroupsOrderColumn = {
  ID: 'ID' as GroupsOrderColumn,
  NAME: 'NAME' as GroupsOrderColumn,
  DESCRIPTION: 'DESCRIPTION' as GroupsOrderColumn,
};
