/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * input for sending invitations from csv
 */
export interface InputInvitationsFromCsv {
  /**
   * values separated with semicolons
   */
  invitationData: Array<string>;
  /**
   * id of VO to send invitation into
   */
  voId: number;
  /**
   * id of Group to send invitation into
   */
  groupId?: number;
  language?: string;
}
