/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents objects, upon which Perun roles can be set, e.g. role RESOURCEADMIN can be set upon Resource, Vo, Facility or no object (None).
 */
export type RoleObject = 'None' | 'Group' | 'Vo' | 'Facility' | 'Resource' | 'User' | 'Member';

export const RoleObject = {
  None: 'None' as RoleObject,
  Group: 'Group' as RoleObject,
  Vo: 'Vo' as RoleObject,
  Facility: 'Facility' as RoleObject,
  Resource: 'Resource' as RoleObject,
  User: 'User' as RoleObject,
  Member: 'Member' as RoleObject,
};
