/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * type of application form items
 */
export type Type =
  | 'HTML_COMMENT'
  | 'SUBMIT_BUTTON'
  | 'AUTO_SUBMIT_BUTTON'
  | 'PASSWORD'
  | 'VALIDATED_EMAIL'
  | 'TEXTFIELD'
  | 'TEXTAREA'
  | 'CHECKBOX'
  | 'RADIO'
  | 'SELECTIONBOX'
  | 'COMBOBOX'
  | 'USERNAME'
  | 'HEADING'
  | 'TIMEZONE'
  | 'EMBEDDED_GROUP_APPLICATION'
  | 'LIST_INPUT_BOX'
  | 'MAP_INPUT_BOX';

export const Type = {
  HTML_COMMENT: 'HTML_COMMENT' as Type,
  SUBMIT_BUTTON: 'SUBMIT_BUTTON' as Type,
  AUTO_SUBMIT_BUTTON: 'AUTO_SUBMIT_BUTTON' as Type,
  PASSWORD: 'PASSWORD' as Type,
  VALIDATED_EMAIL: 'VALIDATED_EMAIL' as Type,
  TEXTFIELD: 'TEXTFIELD' as Type,
  TEXTAREA: 'TEXTAREA' as Type,
  CHECKBOX: 'CHECKBOX' as Type,
  RADIO: 'RADIO' as Type,
  SELECTIONBOX: 'SELECTIONBOX' as Type,
  COMBOBOX: 'COMBOBOX' as Type,
  USERNAME: 'USERNAME' as Type,
  HEADING: 'HEADING' as Type,
  TIMEZONE: 'TIMEZONE' as Type,
  EMBEDDED_GROUP_APPLICATION: 'EMBEDDED_GROUP_APPLICATION' as Type,
  LIST_INPUT_BOX: 'LIST_INPUT_BOX' as Type,
  MAP_INPUT_BOX: 'MAP_INPUT_BOX' as Type,
};
