/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersOrderColumn } from './usersOrderColumn';
import { SortingOrder } from './sortingOrder';


export interface UsersPageQuery { 
    pageSize: number;
    offset: number;
    order: SortingOrder;
    sortColumn: UsersOrderColumn;
    searchString?: string;
    withoutVo?: boolean;
}

