export type LinkerResult =
  | 'OK'
  | 'IDENTITY_UNKNOWN'
  | 'IDENTITY_REGISTERED_ALREADY'
  | 'IDENTITY_LINKED'
  | 'IDENTITY_IDENTICAL'
  | 'TOKEN_EXPIRED'
  | 'UNKNOWN_ERROR'
  | 'MESSAGE_SENT_TO_SUPPORT';
